import type { TFunction } from "i18next";
import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";
import { blankToNull } from "../lib/blankToNull";
import { UNIT_CODES } from "../lib/units";

type CatalogItemInsert = Database["werkbank"]["Tables"]["catalog_items"]["Insert"];

/** A non-negative amount typed with comma or dot and at most two decimals. */
const PRICE = /^\d+([.,]\d{1,2})?$/;

const price = (t: TFunction) => z.string().trim().regex(PRICE, t("catalog.errors.price"));

export const catalogItemSchema = (t: TFunction) =>
  z.object({
    item_no: z.string(),
    name: z.string().trim().min(1, t("catalog.errors.name")),
    description: z.string(),
    category: z.string(),
    unit_code: z.enum(UNIT_CODES, t("catalog.errors.unit")),
    labour_price: price(t),
    material_price: price(t),
    vat_rate: z.enum(["19", "7", "0"], t("catalog.errors.vat")),
  });

export type CatalogItemForm = z.infer<ReturnType<typeof catalogItemSchema>>;

const toNumber = (value: string) => Number(value.replace(",", "."));

/** Form values as a table row: prices and VAT as numbers, blank text as `null`. `org_id` is
 *  added by the caller; `net_price` is generated by the database and never written. */
export function toCatalogItemRow(form: CatalogItemForm): Omit<CatalogItemInsert, "org_id"> {
  const text = blankToNull({
    item_no: form.item_no,
    name: form.name,
    description: form.description,
    category: form.category,
  });
  return {
    item_no: text.item_no,
    name: form.name.trim(),
    description: text.description,
    category: text.category,
    unit_code: form.unit_code,
    labour_price: toNumber(form.labour_price),
    material_price: toNumber(form.material_price),
    vat_rate: Number(form.vat_rate),
  };
}
