// Role display labels for the edge runtime. The block below is the twin of the
// ROLE LABELS MIRROR in src/config/app.config.ts and is regenerated by
// scripts/sync-mirrors.mjs (npm run sync:mirrors); npm run sync:mirrors:check
// fails CI on drift. Do not hand-edit the block — edit the source and regenerate.
// `AppRole` mirrors the frontend enum type so the block can stay byte-identical.
type AppRole = 'admin' | 'producer' | 'artist';
import { VOCABULARY, ORG_KIND_DEFS, DEFAULT_ORG_KIND, roleLabelsFollowUiLanguage, type OrgKind, type OrgKindLang } from './orgKind.ts';

// >>> ROLE LABELS MIRROR (keep byte-identical with the twin file) >>>
/**
 * Human-facing labels for each org role. The `producer` role now covers both
 * show producers and project managers (hire orders), so it reads "Production Team"
 * in the UI (and in the org-invitation email) while the enum value stays `producer` —
 * the DB enum, RLS policies, and edge functions all key off the literal `producer`,
 * so only the display label changes. Mirrored to
 * supabase/functions/_shared/roles.ts (npm run sync:mirrors) so the invite email
 * renders the same label; the surrounding imports differ per runtime.
 */
export const ROLE_LABELS: Record<AppRole, string> = {
  admin: 'Admin',
  producer: 'Production Team',
  artist: 'Artist',
};

/** Language a kind renders its role copy in: the UI language when the kind opts in,
 *  English otherwise (today's behaviour for production and staffing). */
const roleCopyLang = (kind: OrgKind, lang: OrgKindLang): OrgKindLang =>
  roleLabelsFollowUiLanguage(kind) ? lang : 'en';

/** Display label for a role. Tolerant of unknown strings (falls back to the raw value).
 *  The producer and artist labels follow the workspace type (VOCABULARY[kind][lang]);
 *  the table language is the UI language only for kinds that opt in, English otherwise. */
export const roleLabel = (role: string, kind: OrgKind = DEFAULT_ORG_KIND, lang: OrgKindLang = 'en'): string => {
  const vocab = VOCABULARY[kind][roleCopyLang(kind, lang)];
  if (role === 'producer') return vocab.roleProducer;
  if (role === 'artist') return vocab.roleArtist;
  return ROLE_LABELS[role as keyof typeof ROLE_LABELS] ?? role;
};

/**
 * One-sentence explanation of what each role can do, shown wherever someone needs to
 * understand a role before they act on it: the People pane's role dropdown (a caption
 * under each role option) and the accept-invite success screen are the planned
 * consumers, not yet built. The org-invitation email states its own second-person
 * version instead (org-invitation.roleIntroAdmin/Producer/Artist in
 * src/lib/emailTemplates/emailCopy.ts): "You are joining..." cannot grammatically
 * continue into a third-person clause, so review both together when either changes, but
 * they are not required to match word for word. Mirrored to
 * supabase/functions/_shared/roles.ts (npm run sync:mirrors) so every runtime renders
 * the same text; the surrounding imports differ per runtime.
 *
 * Two constraints keep every sentence true regardless of an org's configuration: stays
 * silent on offers and digests (artist acceptance is a per-org toggle, and a
 * direct-book org never opens an offer at all); and states each role's DEFAULT grant,
 * not one invitee's resolved capabilities (several producer permissions are
 * individually org-toggleable, so a producer may not actually get everything this
 * sentence describes).
 *
 * The artist line deliberately says nothing about declaring availability: that action
 * lives behind /availability, itself gated by the booking_flow entitlement (see
 * ROUTE_FEATURES in src/config/app.config.ts), so an org with that module off has
 * artists who cannot reach it at all. An earlier draft hedged with "where that is
 * turned on" to stay true for that case, but a brand-new invitee has no way to decode
 * who turns it on or where, so the sentence omits the claim entirely instead of
 * hedging it. This matches org-invitation.roleIntroArtist, which never mentioned it
 * either.
 */
/** Token templates for the role descriptions. The production vocabulary words equal the
 *  hardcoded English nouns, so the production resolution (ROLE_DESCRIPTIONS below) is
 *  byte-identical to the previous literal map; a staffing org reads its own nouns
 *  ("clients", "shifts", "people", "teams"). Kept as templates so the two workspace types
 *  cannot drift (appConfig.roles.test.ts pins the production resolution to ROLE_DESCRIPTIONS). */
const ROLE_DESCRIPTION_TEMPLATES: Record<AppRole, string> = {
  admin: 'Full control of this workspace, including people, {{casts}}, settings, and every booking.',
  // "show dates" stays literal, matching org-invitation.roleIntroProducer exactly (the
  // twin pinned by appConfig.roles.test.ts): production {{showDates}} resolves to "dates",
  // and both strings deliberately use the fuller phrase, so neither tokenizes it.
  producer: 'Plans {{productions}} and show dates, and books {{artists}} into them.',
  artist: 'Gets booked for {{productions}} and sees every confirmed engagement.',
};

/** Resolve a role description in the org's workspace vocabulary. A kind that sets
 *  `roleDescriptions` supplies full sentences per language; core kinds do not, so they
 *  resolve the English templates below. A bare `{{name}}` substitution keeps this file
 *  importing nothing beyond the org kind registry, so it stays a clean block mirror. */
function resolveRoleDescription(role: string, kind: OrgKind, lang: OrgKindLang = 'en'): string {
  const own = ORG_KIND_DEFS[kind].roleDescriptions;
  if (own) return (own[roleCopyLang(kind, lang)] as Record<string, string>)[role] ?? '';
  const template = ROLE_DESCRIPTION_TEMPLATES[role as keyof typeof ROLE_DESCRIPTION_TEMPLATES];
  if (!template) return '';
  const vocab = VOCABULARY[kind].en as Record<string, string>;
  return template.replace(/\{\{(\w+)\}\}/g, (_m, name) => vocab[name] ?? `{{${name}}}`);
}

/** Production resolution of every role description, byte-identical to the historical
 *  literal map. Consumed directly where a caller has no org kind, and pinned by tests as
 *  the production baseline; prefer roleDescription(role, kind) in kind-aware surfaces. */
export const ROLE_DESCRIPTIONS: Record<AppRole, string> = {
  admin: resolveRoleDescription('admin', DEFAULT_ORG_KIND),
  producer: resolveRoleDescription('producer', DEFAULT_ORG_KIND),
  artist: resolveRoleDescription('artist', DEFAULT_ORG_KIND),
};

/** One-sentence description of what a role can do, in the org's workspace vocabulary.
 *  Tolerant of unknown strings (falls back to an empty string), mirroring roleLabel's
 *  fallback semantics so a future enum value that hasn't been added to the registry yet
 *  degrades to "no second sentence" rather than an undefined-riddled render. */
export function roleDescription(role: string, kind: OrgKind = DEFAULT_ORG_KIND, lang: OrgKindLang = 'en'): string {
  return resolveRoleDescription(role, kind, lang);
}
// <<< ROLE LABELS MIRROR <<<

/** Role label for an invitation email. A kind whose role labels follow the UI language
 *  renders in the org's locale; production and staffing keep today's English label. */
export function inviteRoleLabel(role: string, kind: OrgKind, locale: "en" | "de"): string {
  return roleLabelsFollowUiLanguage(kind) ? roleLabel(role, kind, locale) : roleLabel(role);
}
