// Editable hire-order PDF copy. Every static string the renderer prints is a
// key here; interpolated strings use {{token}} placeholders resolved by
// applyTokens. Per-org overrides live in the `hire_order_copy` app-setting and
// are merged over these defaults by resolveHireOrderCopy.
//
// DUAL-HOME PAIR: src/lib/hireOrders/pdf/pdfCopy.ts (edit here) generates
// supabase/functions/_shared/hire-order-pdf/pdfCopy.ts (the edge renderer
// can't import from src/). After editing the source, run
// `npm run sync:mirrors`; never hand-edit the generated target directly.
// pdfCopyMirror.test.ts and CI's sync:mirrors:check fail if the two drift.
// No relative imports here, since the same body must run unchanged in
// both the browser bundle and the edge runtime.
//
// HOUSE RULE: no em/en dashes in defaults. Use middot, comma, or period.

export type CopyKey =
  // Header + status badge
  | "header_eyebrow"
  | "badge_preview"
  | "badge_countersigned"
  | "badge_issued"
  // Title
  | "title_lead"
  | "billing_role_and_cast"
  | "billing_cast_only"
  // Parties
  | "party_producer_label"
  | "party_agent"
  | "party_artist_label"
  | "party_cast_reference"
  | "party_engagement"
  // Facts strip
  | "facts_date_label"
  | "facts_dates_count"
  | "facts_venue_label"
  | "facts_performance_label"
  | "facts_duration"
  | "facts_sessions_count"
  | "facts_single_set"
  | "facts_fee_label"
  | "facts_fee_sub"
  // Engagement dates + running order
  | "engagement_dates_heading"
  | "session_label"
  | "running_order_heading_venue"
  | "running_order_heading"
  | "table_call"
  | "table_time"
  // Notes
  | "notes_prefix"
  // Fees
  | "fees_heading"
  | "fees_engagement_fee"
  | "fees_per_date"
  | "fees_per_date_single"
  | "fees_total"
  // Terms
  | "terms_heading"
  // Signatures
  | "signature_for_producer"
  | "signature_producer_hint"
  | "signature_for_artist"
  | "signature_signed_electronically"
  | "signature_artist_hint"
  // Watermark
  | "watermark"
  // Footer
  | "footer_generated"
  // Certificate page
  | "cert_heading"
  | "cert_lead"
  | "cert_signer"
  | "cert_email"
  | "cert_method"
  | "cert_method_drawn"
  | "cert_method_typed"
  | "cert_signed_at"
  | "cert_signed_at_value"
  | "cert_ip"
  | "cert_device"
  | "cert_sha";

export type HireOrderCopy = Record<CopyKey, string>;

export const HIRE_ORDER_COPY_DEFAULTS: HireOrderCopy = {
  header_eyebrow: "Performance contract",
  badge_preview: "Preview",
  badge_countersigned: "Countersigned",
  badge_issued: "Issued",

  title_lead: "This contract confirms the engagement of",
  billing_role_and_cast: "{{role}} · billed as {{castRef}}",
  billing_cast_only: "Billed as {{castRef}}",

  party_producer_label: "Hiring party, the Producer",
  party_agent: "Booking agent: {{agent_name}}",
  party_artist_label: "Engaged artist, the Artist",
  party_cast_reference: "Cast reference: {{castRef}}",
  party_engagement: "Engagement: {{role}}",

  facts_date_label: "Date",
  facts_dates_count: "{{count}} dates",
  facts_venue_label: "Venue",
  facts_performance_label: "Performance",
  facts_duration: "{{duration}} min",
  facts_sessions_count: "{{count}} sessions",
  facts_single_set: "Single set",
  facts_fee_label: "Engagement fee",
  facts_fee_sub: "net of VAT",

  engagement_dates_heading: "Engagement dates",
  session_label: "Session {{n}}",
  running_order_heading_venue: "Running order, {{venue}}",
  running_order_heading: "Running order",
  table_call: "Call",
  table_time: "Time",

  notes_prefix: "Notes: {{notes}}",

  fees_heading: "Fees & payment schedule",
  fees_engagement_fee: "Engagement fee",
  fees_per_date: "{{amount}} per date x {{count}} dates",
  fees_per_date_single: "{{amount}} per date",
  fees_total: "Total payable",

  terms_heading: "Terms & conditions",

  signature_for_producer: "For the Producer · {{legal_name}}",
  signature_producer_hint: "Name · Date {{date}}",
  signature_for_artist: "The Artist · {{artistName}}",
  signature_signed_electronically: "Signed electronically · {{date}}",
  signature_artist_hint: "Signature · Date",

  watermark: "PREVIEW",

  footer_generated: "Generated by ShowFlow Pro · {{date}}",

  cert_heading: "Signature certificate",
  cert_lead: "Electronic signature record for contract {{orderNo}}.",
  cert_signer: "Signer",
  cert_email: "Email",
  cert_method: "Method",
  cert_method_drawn: "Drawn signature",
  cert_method_typed: "Typed signature",
  cert_signed_at: "Signed at",
  cert_signed_at_value: "{{datetime}} (UTC)",
  cert_ip: "IP address",
  cert_device: "Device",
  cert_sha: "Document SHA-256",
};

/** Complete German base map for the hire-order PDF. Same keys as
 *  HIRE_ORDER_COPY_DEFAULTS (enforced by pdfCopy.test.ts key/placeholder/Du/dash
 *  gates); selected by resolveHireOrderCopy(overrides, "de"). Contract register
 *  with informal Du address, no dashes, Engagementvertrag glossary. Mirrored to
 *  the edge with this file. */
export const HIRE_ORDER_COPY_DE: HireOrderCopy = {
  header_eyebrow: "Engagementvertrag",
  badge_preview: "Vorschau",
  badge_countersigned: "Gegengezeichnet",
  badge_issued: "Ausgestellt",

  title_lead: "Dieser Engagementvertrag bestätigt das Engagement von",
  billing_role_and_cast: "{{role}} · gebucht als {{castRef}}",
  billing_cast_only: "Gebucht als {{castRef}}",

  party_producer_label: "Auftraggeber, der Produzent",
  party_agent: "Buchungsagentur: {{agent_name}}",
  party_artist_label: "Engagierter Artist, der Artist",
  party_cast_reference: "Besetzung: {{castRef}}",
  party_engagement: "Engagement: {{role}}",

  facts_date_label: "Datum",
  facts_dates_count: "{{count}} Termine",
  facts_venue_label: "Location",
  facts_performance_label: "Auftritt",
  facts_duration: "{{duration}} Min.",
  facts_sessions_count: "{{count}} Einheiten",
  facts_single_set: "Einzelset",
  facts_fee_label: "Engagementhonorar",
  facts_fee_sub: "netto zzgl. MwSt.",

  engagement_dates_heading: "Engagementtermine",
  session_label: "Einheit {{n}}",
  running_order_heading_venue: "Ablaufplan, {{venue}}",
  running_order_heading: "Ablaufplan",
  table_call: "Einsatz",
  table_time: "Uhrzeit",

  notes_prefix: "Hinweise: {{notes}}",

  fees_heading: "Honorar & Zahlungsplan",
  fees_engagement_fee: "Engagementhonorar",
  fees_per_date: "{{amount}} pro Termin x {{count}} Termine",
  fees_per_date_single: "{{amount}} pro Termin",
  fees_total: "Gesamtbetrag fällig",

  terms_heading: "Allgemeine Geschäftsbedingungen",

  signature_for_producer: "Für den Produzenten · {{legal_name}}",
  signature_producer_hint: "Name · Datum {{date}}",
  signature_for_artist: "Der Artist · {{artistName}}",
  signature_signed_electronically: "Elektronisch unterschrieben · {{date}}",
  signature_artist_hint: "Unterschrift · Datum",

  watermark: "VORSCHAU",

  footer_generated: "Erstellt von ShowFlow Pro · {{date}}",

  cert_heading: "Signaturzertifikat",
  cert_lead: "Datensatz zur elektronischen Signatur für Engagementvertrag {{orderNo}}.",
  cert_signer: "Unterzeichner",
  cert_email: "E-Mail",
  cert_method: "Methode",
  cert_method_drawn: "Handgezeichnete Signatur",
  cert_method_typed: "Getippte Signatur",
  cert_signed_at: "Unterschrieben am",
  cert_signed_at_value: "{{datetime}} (UTC)",
  cert_ip: "IP-Adresse",
  cert_device: "Gerät",
  cert_sha: "Dokument SHA-256",
};

/** Replace each {{token}} whose name is a key of `values`. Unknown {{...}} are
 *  left verbatim (a typo stays visible instead of blanking or injecting). */
export function applyTokens(
  template: string,
  values: Record<string, string | number>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : whole,
  );
}

/** Plain {{name}} substitution from a resolved vocabulary table. A local, import-free
 *  copy of interpolateVocabulary (src/lib/orgKind.ts): this file is a whole-file mirror
 *  that must import nothing (the edge twin resolves ../orgKind at a different relative
 *  depth than this source's ../../orgKind, so no single import path works on both sides).
 *  Unknown tokens (the runtime data tokens {{castRef}}, {{artistName}}, {{role}}, dates,
 *  counts) are left verbatim for applyTokens. */
function substituteVocabulary(text: string, vocab: Record<string, string>): string {
  return text.replace(/\{\{(\w+)\}\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(vocab, name) ? vocab[name] : whole,
  );
}

/** Production vocabulary fallback, used when resolveHireOrderCopy is called WITHOUT an
 *  explicit vocab table (the caller threads the org's workspace-type table in; until it
 *  does, and for every plain call, this stands in). Its words MUST equal
 *  VOCABULARY.production in src/lib/orgKind.ts, which is exactly what keeps a plain
 *  resolveHireOrderCopy(...) byte-identical to the pre-variable prose. Import-free by the
 *  mirror rule above. */
export const PRODUCTION_VOCAB: Record<"en" | "de", Record<string, string>> = {
  en: {
    show: "show", shows: "shows", Show: "Show", Shows: "Shows",
    showDate: "date", showDates: "dates", ShowDate: "Date", ShowDates: "Dates",
    artist: "artist", artists: "artists", Artist: "Artist", Artists: "Artists",
    production: "production", productions: "productions", Production: "Production", Productions: "Productions",
    cast: "cast", casts: "casts", Cast: "Cast", Casts: "Casts",
    understudy: "understudy", understudies: "understudies", Understudy: "Understudy", Understudies: "Understudies",
    skill: "skill", skills: "skills", Skill: "Skill", Skills: "Skills",
    hireOrder: "contract", hireOrders: "contracts", HireOrder: "Contract", HireOrders: "Contracts",
    roleProducer: "Production Team", roleArtist: "Artist", kind: "production",
  },
  de: {
    show: "Show", shows: "Shows", Show: "Show", Shows: "Shows",
    showDate: "Termin", showDates: "Termine", ShowDate: "Termin", ShowDates: "Termine",
    artist: "Artist", artists: "Artists", Artist: "Artist", Artists: "Artists",
    production: "Produktion", productions: "Produktionen", Production: "Produktion", Productions: "Produktionen",
    cast: "Besetzung", casts: "Besetzungen", Cast: "Besetzung", Casts: "Besetzungen",
    understudy: "Zweitbesetzung", understudies: "Zweitbesetzungen", Understudy: "Zweitbesetzung", Understudies: "Zweitbesetzungen",
    skill: "Skill", skills: "Skills", Skill: "Skill", Skills: "Skills",
    hireOrder: "Engagementvertrag", hireOrders: "Engagementverträge", HireOrder: "Engagementvertrag", HireOrders: "Engagementverträge",
    roleProducer: "Production Team", roleArtist: "Artist", kind: "production",
  },
};

/**
 * Vocabulary templates: the copy keys that name a domain noun, authored with {{noun}}
 * variables. resolveHireOrderCopy substitutes these against the resolved workspace-type
 * table (staffing swaps the words) for any key still at its language default. Kept
 * SEPARATE from HIRE_ORDER_COPY_DEFAULTS / HIRE_ORDER_COPY_DE, which stay clean prose,
 * because render.tsx reads `input.copy ?? HIRE_ORDER_COPY_DEFAULTS` and sampleDocument.ts
 * plus the render tests read the default maps RAW, so a bare {{Cast}} token in the
 * defaults would leak into any direct or default render. Under the production table every
 * value here substitutes back to the exact clean default, which is the byte-identity
 * guarantee (guarded by pdfCopy.orgKind.test.ts). Only nouns whose production word equals
 * the current literal are tokenized, so the runtime tokens {{castRef}}/{{artistName}} are
 * left untouched here and filled later by applyTokens. */
const HIRE_ORDER_COPY_VOCAB_TEMPLATES: Record<"en" | "de", Partial<Record<CopyKey, string>>> = {
  en: {
    // {{hireOrder}}="contract" (prod, byte-identical to the new default) / "work order"
    // (staffing). {{HireOrder}} title-cased where the sentence starts with it.
    header_eyebrow: "Performance {{hireOrder}}",
    title_lead: "This {{hireOrder}} confirms the engagement of",
    cert_lead: "Electronic signature record for {{hireOrder}} {{orderNo}}.",
    party_artist_label: "Engaged {{artist}}, the {{Artist}}",
    party_cast_reference: "{{Cast}} reference: {{castRef}}",
    signature_for_artist: "The {{Artist}} · {{artistName}}",
  },
  de: {
    // {{HireOrder}}="Engagementvertrag" (prod, byte-identical to the DE default) /
    // "Arbeitsauftrag" (staffing).
    header_eyebrow: "{{HireOrder}}",
    title_lead: "Dieser {{HireOrder}} bestätigt das Engagement von",
    cert_lead: "Datensatz zur elektronischen Signatur für {{HireOrder}} {{orderNo}}.",
    // party_artist_label and signature_for_artist are deliberately NOT tokenized in German.
    // They carry gender agreement ("Engagierter ... der ...", "Der ...") that is correct for
    // the masculine production noun "Artist" (der Artist) but wrong for staffing's neuter
    // "Teammitglied" (das Teammitglied) — a plain {{noun}} substitution cannot re-agree the
    // article/adjective. So they stay at the clean DE default (production noun, grammatical)
    // for both kinds, the same tradeoff as party_producer_label. English has no such
    // agreement, so its templates above still swap. title_lead is safe: {{HireOrder}} is
    // masculine in both kinds (der Engagementvertrag / der Arbeitsauftrag).
    party_cast_reference: "{{Cast}}: {{castRef}}",
  },
};

/** Merge per-org overrides over the defaults, then substitute {{noun}} vocabulary
 *  variables. A blank/whitespace override falls back to the default; the result is always
 *  a complete record.
 *
 *  `vocab` is a RESOLVED vocabulary table (VOCABULARY[kind][locale] shape, typed
 *  structurally as Record<string, string> so this file imports nothing). When omitted it
 *  falls back to the production words for `locale`; since those equal the hardcoded
 *  nouns, a plain call (or a production table) is byte-identical to before {{noun}}
 *  variables existed. A staffing table swaps the words. A key still at its language
 *  default draws its noun from the vocabulary template above; a key an admin overrode is
 *  substituted as authored, so a {{Show}} in a custom string still resolves. The runtime
 *  data tokens {{castRef}}, {{artistName}}, {{role}} and every other {{...}} are left for
 *  applyTokens. */
export function resolveHireOrderCopy(
  overrides?: Partial<HireOrderCopy> | null,
  locale: "en" | "de" = "en",
  vocab?: Record<string, string>,
): HireOrderCopy {
  // Select the language base; a sparse per-org override still layers on top.
  // English (default) stays byte-identical, so the edge renderer is unchanged
  // for every org that has not opted into German.
  const base = locale === "de" ? HIRE_ORDER_COPY_DE : HIRE_ORDER_COPY_DEFAULTS;
  const out = { ...base };
  if (overrides) {
    for (const key of Object.keys(HIRE_ORDER_COPY_DEFAULTS) as CopyKey[]) {
      const v = overrides[key];
      if (typeof v === "string" && v.trim() !== "") out[key] = v;
    }
  }
  const table = vocab ?? PRODUCTION_VOCAB[locale];
  const templates = HIRE_ORDER_COPY_VOCAB_TEMPLATES[locale];
  for (const key of Object.keys(out) as CopyKey[]) {
    const overridden = out[key] !== base[key];
    let source = overridden ? out[key] : (templates[key] ?? out[key]);
    // Backward-compat: a per-org override saved before Task 2 may still contain the old
    // runtime tokens {{cast}}/{{artist}} (the names the PDF editor documented before they
    // were renamed to {{castRef}}/{{artistName}} to avoid colliding with the cast/artist
    // vocabulary keys). In a customized value those always meant the runtime cast/artist
    // name, so rewrite them to the new names before the vocabulary pass; otherwise the
    // vocab pass would turn {{cast}} into the noun and applyTokens, which now fills only
    // castRef/artistName, would never resolve it. Defaults/templates already use the new
    // names and skip this branch.
    if (overridden) {
      source = source.replace(/\{\{cast\}\}/g, "{{castRef}}").replace(/\{\{artist\}\}/g, "{{artistName}}");
    }
    out[key] = substituteVocabulary(source, table);
  }
  return out;
}
